develop to master
kbaseapps/SetAPI pull request #47
Opened 2021-03-12 18:28 UTC by Yzm1234

2021-03-17 17:13 UTC, sychan requested changes

2021-03-17 17:13 UTC, sychan commented on kbase.yml
>      [wjriehl, tgu2, slebras]
Please add your own ID to this list so that you can request a release of the app.

2021-03-17 18:56 UTC, Yzm1234 commented on kbase.yml
>      [wjriehl, tgu2, slebras]
Done

2021-03-19 16:18 UTC, sychan approved these changes

2021-03-19 16:18 UTC, merged